# .circleci/config.yml

version: 2.1

jobs:
  try-first-job:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "I am a job name try first job within workflow named "


  try-second-job:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run:
         name: fastlane
         command: bundle exec fastlane uploadBuildToFirebase


workflows:
  try_first_workflow:
    jobs:
      - try-first-job
      - try-second-job