# .circleci/config.yml

version: 2.1

jobs:
  try-first-job:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "I am a job name try first job within workflow named "

  try-second-job:
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            echo 'export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"' >> $BASH_ENV
            echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> $BASH_ENV

      - run:
          name: Check Java Version
          command: java -version
      - run:
          name: Install Dependencies
          command: bundle install
      - run:
          name: fastlane
          command: bundle exec fastlane uploadBuildToFirebase

workflows:
  try_first_workflow:
    jobs:
      - try-first-job
      - try-second-job
