version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      # ... (your existing steps)

      - run:
          name: Install Firebase CLI
          command: |
            curl -sL https://firebase.tools | bash

      - run:
          name: Distribute APK to Firebase
          command: |
            ./firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk --app 1:334977791104:android:a2086173c5bbecade82265 --token $FIREBASE_CLI_TOKEN --groups "My Group"
