# .circleci/config.yml

version: 2.1

jobs:
  try-first-job:
    macos:
      xcode: 14.0.1
    steps:
      - run: echo "I am a job name try first job within workflow named "


workflow:
  try_first_workflow:
    jobs:
      - try-first-job